spring:
#  main.banner-mode: off
  jpa:
    database: postgresql
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.show-sql: true
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/examplevertx
    username: postgres
    password: postgres
